spring.application.name=foodie
app.version=@project.version@

server.port=${SERVER_PORT}
api.prefix=${API_PREFIX}
frontend.url=${FRONTEND_URL}

jwt.secret=${JWT_SECRET}

app.admin.email=${ADMIN_EMAIL}
app.admin.password=${ADMIN_PASSWORD}
app.admin.full-name=${ADMIN_FULL_NAME}
app.admin.phone-number=${ADMIN_PHONE_NUMBER}

spring.security.user.name=${SPRING_SECURITY_USER_NAME}
spring.security.user.password=${SPRING_SECURITY_USER_PASSWORD}

spring.datasource.url=${SPRING_DATASOURCE_URL}
spring.datasource.username=${SPRING_DATASOURCE_USERNAME}
spring.datasource.password=${SPRING_DATASOURCE_PASSWORD}

spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver
spring.servlet.multipart.enabled=true
spring.servlet.multipart.max-file-size=10MB
spring.servlet.multipart.max-request-size=10MB

spring.jpa.show-sql=true
spring.jpa.generate-ddl=true
spring.jpa.hibernate.ddl.auto=update
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.MySQL8Dialect

# Giup frontend gui kieu enum khong phan biet viet hoa viet thuong
spring.jackson.mapper.accept_case_insensitive_enums=true

